/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: paskaraita (https://sketchfab.com/paskaraita)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/hello-my-friends-9c20a10f2352406fa90485fafc531fa9
title: Hello my friends
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/robot.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -1]} rotation={[Math.PI, 0, 0]} scale={0.05}>
          <group rotation={[-Math.PI, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <group position={[-0.23, -1.16, 0]}>
              <mesh
                geometry={nodes["hahmo_01_-_Default_0"].geometry}
                material={materials["01_-_Default"]}
              />
            </group>
            <group
              position={[-6.24, -10.22, 8.23]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes["silm��t_03_-_Default_0"].geometry}
                material={nodes["silm��t_03_-_Default_0"].material}
              />
            </group>
            <group position={[-4.32, -1.25, -4.64]} scale={[0.9, 0.9, 1]}>
              <mesh
                geometry={nodes["jalat_07_-_Default_0"].geometry}
                material={nodes["jalat_07_-_Default_0"].material}
              />
            </group>
            <group position={[0.16, -1.67, -5.12]}>
              <mesh
                geometry={nodes["Cylinder004_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
              />
            </group>
            <group position={[21.58, 0, 24.97]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes["Plane001_02_-_Default_0"].geometry}
                material={materials["02_-_Default"]}
              />
            </group>
            <group
              position={[-0.34, -10.9, 5.5]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 1, 0.24]}
            >
              <mesh
                geometry={nodes["suu_03_-_Default_0"].geometry}
                material={nodes["suu_03_-_Default_0"].material}
              />
            </group>
            <group position={[-0.23, -1.16, 0]}>
              <mesh
                geometry={nodes["hahmo_reunat_09_-_Default_0"].geometry}
                material={nodes["hahmo_reunat_09_-_Default_0"].material}
              />
            </group>
            <group position={[-4.32, -1.25, -4.64]} scale={[0.9, 0.9, 1]}>
              <mesh
                geometry={nodes["jalat_reunat_09_-_Default_0"].geometry}
                material={nodes["jalat_reunat_09_-_Default_0"].material}
              />
            </group>
            <skinnedMesh
              geometry={nodes["k��det_07_-_Default_0"].geometry}
              material={nodes["k��det_07_-_Default_0"].material}
              skeleton={nodes["k��det_07_-_Default_0"].skeleton}
            />
            <skinnedMesh
              geometry={nodes["k��det_reuna_09_-_Default_0"].geometry}
              material={nodes["k��det_reuna_09_-_Default_0"].material}
              skeleton={nodes["k��det_reuna_09_-_Default_0"].skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot.gltf");
